version = "3.7.15"
runner.dialect = scala213source3
project.git = true
rewrite.rules = [RedundantParens, PreferCurlyFors, SortModifiers]
indent.ctrlSite = 2
maxColumn = 150
align.openParenDefnSite = true
