# Duplicated from explorer-backend
version = 3.7.14
runner.dialect = scala213source3
project.git = true
align.preset = more
rewrite.rules = [RedundantParens, PreferCurlyFors, SortModifiers]
maxColumn = 100
assumeStandardLibraryStripMargin = true
align.stripMargin = true

# Additions
newlines.implicitParamListModifierPrefer = before
newlines.beforeCurlyLambdaParams = multiline
docstrings.style = Asterisk
docstrings.wrap = no
align.closeParenSite = false
align.openParenDefnSite = true
align.openParenCallSite = true
danglingParentheses.callSite = true
optIn.configStyleArguments = true
binPack.parentConstructors = Always
