name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt

      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
        shell: bash
      - run: sbt "compile; lsp-server/assembly; universal:packageBin"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update version in package.json
        run: |
          cd plugin-vscode
          jq --arg version "${{ steps.get_version.outputs.VERSION }}" '.version = $version' package.json > tmp_package.json && mv tmp_package.json package.json

      - name: Package VSCode Extension
        run: |
          sbt copyJARToVSCode
          cd plugin-vscode
          npm install -g vsce
          npm install
          vsce package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body: Some solid code
          draft: false
          prerelease: false

      - name: Upload Release Asset (Jar)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lsp-server/target/scala-2.13/ralph-lsp.jar
          asset_name: ralph-lsp-${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Upload Release Asset (Universal zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/universal/ralph-lsp-0.1.0-SNAPSHOT.zip
          asset_name: ralph-lsp-${{ steps.get_version.outputs.VERSION }}.zip
         asset_content_type: application/zip

      - name: Upload Release Asset (VSCode Extension)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: plugin-vscode/ralph-lsp-${{ steps.get_version.outputs.VERSION }}.vsix
          asset_name: ralph-lsp-${{ steps.get_version.outputs.VERSION }}.vsix
          asset_content_type: application/octet-stream

#      - name: Publish VSCode Extension
#        env:
#          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
#        run: |
#          cd plugin-vscode
#          vsce publish -p $VSCE_TOKEN
